### ISSUE TITLE
Narvar.com - potential false positive

### ISSUE THREAD

**Issue by lightswitch05** [llacb47/mischosts#1]
Hello,

`narvar.com` does have tracking, but it is shipment delivery tracking (like USPS, UPS, FedEx, etc). I know Bed Bath and Beyond use them. Also Walmart. If you place an order from either of those sites (along with many others), then go into your 'account' to view or order details, all the shipping information comes from Narvar. I used to block them too and eventually removed most of their hosts. From their website:

> A platform designed from the ground up to drive long-term customer loyalty. Pre-purchase delivery prediction, branded package tracking, seamless returns and exchanges, in-store experiences, and beyond.

The tricky part is when they say *branded package tracking*, they are talking about shipment/delivery tracking. The do have `analytics.narvar.com` - which *should* be blocked. 

Here is a related ticket: https://github.com/StevenBlack/hosts/issues/724

From here you can see how I've had many commits removing more and more narvar hosts from being blocked: https://github.com/lightswitch05/hosts/search?q=narvar&type=Commits

anyways, just thought I would share my experience with blocking `narvar.com`.

**Comment by liamengland1** [comment]
Thanks for the heads-up =) 

Closed in https://github.com/llacb47/mischosts/commit/a8420d0d392ca253fdee2ff70318878498b47b0a
