### ISSUE TITLE
[TikTok] New Domains

### ISSUE THREAD

**Issue by Bryantdl7** [llacb47/mischosts#10]
Seriously bytedance feels more like malware every day.... The amount of domains they use is insane. 

Some of these domains may be redundant, I had to go on a bit of a blocking spree because some of them just kept working until I rebooted my phone. Sorry in advance for that. 

ssl.cdn.tiktok.com.c.footprint.net  
log16-normal-c-useast1a.tiktokv.com
pull-rtmp-f1.tiktokcdn.com.wsdvs.com
pull-q5.tiktokcdn.com.c.worldfcdn.com
pull-flv-l11.tiktokcdn.com

pull-rtmp-f1-ab.tiktokcdn.com.wsdvs.com

(\.|^)byteoversea\.com$

(\.|^)tiktokcdn\.com$

(\.|^)tiktokv\.com$

p16-tiktok-va.ibyteimg.com

v19.tiktokcdn.com

a1964.mm2.akamai.net

video.h1.bytedance.map.fastly.net

pull-rtmp-f1-ab.tiktokcdn.com

**Comment by lightswitch05** [comment]
Also seeing `p16-tiktokcdn-com.akamaized.net` in my pihole logs. Kinda concerning since no one in my household uses that trash.

**Comment by lightswitch05** [comment]
* `p16-tiktok-va.ibyteimg.com`
* `p16-va-tiktok.ibyteimg.com`
* `v16m.tiktokcdn.com`
* `v19.tiktokcdn.com`
* `v16.tiktokcdn.com`

**Comment by Bryantdl7** [comment]
In my digging I saw that Vimeo uses some of the same CDNs, maybe that’s the correlation.

Either way, I have to block TikTok because of the various security concerns in the news. Wouldn’t be surprised if it’s a country-wide ban soon like India did.


Sent from my iPhone

On Jul 17, 2020, at 9:05 AM, Daniel <notifications@github.com> wrote:

﻿

  *   p16-tiktok-va.ibyteimg.com
  *   p16-va-tiktok.ibyteimg.com
  *   v16m.tiktokcdn.com
  *   v19.tiktokcdn.com
  *   v16.tiktokcdn.com

**Comment by liamengland1** [comment]
Added a few missing: https://github.com/llacb47/mischosts/commit/609c6fbe564e30b206a8beb253a7a397f5e1cb1e

I had most of those domains already, plus a lot more: https://raw.githubusercontent.com/llacb47/mischosts/master/social/tiktok-block
