### ISSUE TITLE
Add domains in blocklist

### ISSUE THREAD

**Issue by alsoGAMER** [llacb47/mischosts#14]
Add these domains into the list:

taobao.com
taobao.net
tbsandbox.com
amap.com
189.cn
aliyuncs.com
21cn.com
cmbchina.com
ixigua.com

> They aren't linked directly to TikTok but are owned/used by the same company that owns TikTok.

**Comment by liamengland1** [comment]
Sorry for not getting back to this, I promise I'm not ignoring it. I'll address it soon.
