### ISSUE TITLE
False Positive: substrate.office.com is a CNAME for outlook.office.com

### ISSUE THREAD

**Issue by p1r473** [llacb47/mischosts#16]
Hi,
substrate.office.com is a CNAME for outlook.office.com
The Office substrate is a critical part of enabling services that run across different applications like Exchange Online, SharePoint Online, Teams, and so on.

This domain is not malicious and is not spyware or adaware.

**Comment by liamengland1** [comment]
Fixed with https://github.com/llacb47/mischosts/commit/f91f41253673b4f0d123ffae014c1196bb0bf0fe
