### ISSUE TITLE
Feature request - combined list

### ISSUE THREAD

**Issue by pallebone** [llacb47/mischosts#18]
Hi there, 

Thank you for your work. Is there any chance you would consider keeping a single combined list of all the lists you create so a single pull is possible from your repo?

Kind regards
Peter

**Comment by liamengland1** [comment]
Hi, sorry I didn't see this, I really need to manage my github notifications better. Can you elaborate on what you mean? What lists do you think should be combined?

**Comment by pallebone** [comment]
Hello,

Thank you for your reply. Its not really a problem, thank you. I just added each on manually. Sorry for wasting your time :)

kind regards 
Pete
