### ISSUE TITLE
msh.amazon.com 

### ISSUE THREAD

**Issue by p1r473** [llacb47/mischosts#20]
Hi @llacb47
This domain seems to break thumbnails for items in certain parts of the Amazon app
https://github.com/ftpmorph/ftprivacy/issues/7

**Comment by liamengland1** [comment]
Can you be more specific? Thumbnails seem to be loading fine for me right now. The domain seems to be used for A/B testing (aka Weblab)

**Comment by p1r473** [comment]
I will close and reopen if I can replicate. Thanks.
