### ISSUE TITLE
Can't sign in on Firefox on laptop or in the Android app

### ISSUE THREAD

**Issue by BrodyStone21** [llacb47/mischosts#29]
I have to whitelist the below domains in order to sign in. 

starling-oversea.byteoversea.com
verification-va.byteoversea.com
mcs-va.tiktok.com
vcs-va.byteoversea.com

**Comment by ABJ4403** [comment]
what?? how whitelisting tiktok domain can even fix that??? i didnt have this problem (btw)

**Comment by BrodyStone21** [comment]
Closing this because I don't know how my original solution fixed the issue for me. I didn't even think about them being tik tok domains...
