### ISSUE TITLE
Add Microsoft Telemetry/Marketing: statics-marketingsites-eus-ms-com.akamaized.net

### ISSUE THREAD

**Issue by rugabunda** [llacb47/mischosts#6]
microsoft marketing

statics-marketingsites-eus-ms-com.akamaized.net
statics-marketingsites-wcus-ms-com.akamaized.net

Saw this connecting via svchost.exe, windows 10 1903 Enterprise

you can connect to them directly in your browser and see

**Comment by rugabunda** [comment]
found it listed here as well https://www.netify.ai/resources/applications/microsoft

**Comment by rugabunda** [comment]
![Svchost exe](https://user-images.githubusercontent.com/38260267/83578811-333a7c80-a527-11ea-918a-5b52dd5ef447.png)

**Comment by rugabunda** [comment]
these domains are unlisted on microsofts public endpoint connections lists or [GDPR compliance documents, ](https://www.scribd.com/document/410614644/MSWin10-GDPR-Compliance-pdf)

**Comment by liamengland1** [comment]
I think those domains are just CDNs for images/CSS. `https://statics-marketingsites-eus-ms-com.akamaized.net/statics/override.css?c=7`

Unless you find evidence of spying or tracking endpoints, I'm not blocking it.
